### ISSUE TITLE
Authentication is required for rubygems.org

### ISSUE THREAD

**Issue by brianmay** [manveru/bundix#108]
```
Downloading /home/brian/.cache/bundix/https_rubygems_org_gems_sass-embedded-1_63_6-x86_64-linux_gem from https://rubygems.org/gems/sass-embedded-1.63.6-x86_64-linux.gem
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/source.rb:23: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Authentication is required for rubygems.org.
Please supply credentials for this source. You can do this by running:
 bundle config packages.shopify.io username:password
403 Forbidden
Skipping sass-embedded: couldn't fetch hash for sass-embedded-1.63.6-x86_64-linux
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/source.rb:152:in `convert_rubygems'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/source.rb:130:in `convert'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix.rb:92:in `convert_spec'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix.rb:45:in `block in convert'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix.rb:44:in `reverse_each'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix.rb:44:in `with_object'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix.rb:44:in `convert'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:149:in `build_gemset'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:36:in `run'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:22:in `run'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/lib/ruby/gems/2.7.0/gems/bundix-2.5.0/bin/bundix:5:in `<top (required)>'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/bin/.bundix-wrapped:18:in `load'
/nix/store/ja6k9mixk5wc3m6wr5lwn8fjfsv0dp6h-bundix-2.5.1/bin/.bundix-wrapped:18:in `<main>'
```

I tried following the instructions, but it didn't help.

**Comment by brianmay** [comment]
Problem just vanished. Possibly something I did wrong, but error is confusing, so I will leave this open.
