### ISSUE TITLE
Bundix fails to install gem if binary has unicode character in its name (e.g. emoji)

### ISSUE THREAD

**Issue by adc-amatosov** [manveru/bundix#19]
xcode-install uses 🚀 for bin name

Here is example gemfile:
```
source 'https://rubygems.org'

ruby '>= 2.3.0'

gem "xcode-install"
```

nix-build fails with the following error:
```
/nix/store/lb2fn9h6bj6k531izcd065dcdrvwvcr5-gen-bin-stubs.rb:21:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from /nix/store/lb2fn9h6bj6k531izcd065dcdrvwvcr5-gen-bin-stubs.rb:21:in `block in <main>'
	from /nix/store/lb2fn9h6bj6k531izcd065dcdrvwvcr5-gen-bin-stubs.rb:17:in `each'
	from /nix/store/lb2fn9h6bj6k531izcd065dcdrvwvcr5-gen-bin-stubs.rb:17:in `<main>'
builder for ‘/nix/store/lnka6dfxdj6yjlnxsxvwicirbiqj6458-gems.drv’ failed with exit code 1
```

Output of locale:
```
locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by manveru** [comment]
Thanks for the report, this is actually a bug in nixpkgs. I made a PR for it, will see if we can merge it soon.

**Comment by adc-amatosov** [comment]
Thanks for quick response!

**Comment by adc-amatosov** [comment]
Fix works well. Thank you for quick fix!
