### ISSUE TITLE
git submodules are not cloned

### ISSUE THREAD

**Issue by ghost** [manveru/bundix#46]
This is at the top of my Gemfile.lock:

```
GIT
  remote: https://github.com/tmm1/http_parser.rb
  revision: 54b17ba8c7d8d20a16dfc65d1775241833219cf2
  ref: 54b17ba8c7d8d20a16dfc65d1775241833219cf2
  specs:
    http_parser.rb (0.6.1)
```

http_parser fails to build, because the git submodule in ext/ruby_http_parser/vendor/http-parser is not cloned.

```
    current directory: /nix/store/0gx1ydxnqab5crprz48bwz0vjprnmq39-ruby2.6.1-http_parser.rb-0.6.1/lib/ruby/gems/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser
/nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/bin/ruby -I /nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/lib/ruby/2.6.0 -r ./siteconf20190322-697-aqdpkf.rb extconf.rb ''
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/bin/$(RUBY_BASE_NAME)
extconf.rb:17:in `read': No such file or directory @ rb_sysopen - /nix/store/0gx1ydxnqab5crprz48bwz0vjprnmq39-ruby2.6.1-http_parser.rb-0.6.1/lib/ruby/gems/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser/vendor/http-parser/http_parser.c (Errno::ENOENT)
        from extconf.rb:17:in `block (2 levels) in <main>'
        from extconf.rb:16:in `open'
        from extconf.rb:16:in `block in <main>'
        from extconf.rb:15:in `each'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1
```

**Comment by alyssais** [comment]
While it's true that Bundix doesn't currently have submodule support, your lockfile doesn't have `submodules: true`, so Bundler shouldn't install submodules either.

**Comment by ghost** [comment]
`bundler` runs successfully with the same Gemfile.lock. It is available from https://github.com/tootsuite/mastodon/

**Comment by alyssais** [comment]
@petabyteboy I think I've figured out what's going on.

Bundler _does not_ clone the submodules, but then ext/ruby_http_parser/extconf.rb contains the following:

```ruby
xsystem 'git submodule init'
xsystem 'git submodule update'
```

Obviously, this won't work in Nix.

So, you have two options here, neither of which is a fix for Bundix:

1. Patch the Gemfile and Gemfile.lock to clone submodules
2. Use gemConfig to force fetchSubmodules to be set to true for git clones of http-parser.rb

Option 1 is probably best if you can get it upstreamed into Mastodon. Even though it works without `submodules: true`, they really shouldn’t be relying on such behaviour.
