### ISSUE TITLE
Bundix can't find Bundler 2.0.1

### ISSUE THREAD

**Issue by mkaito** [manveru/bundix#50]
I've got a local overlay that looks something like this:

```nix
super: self:
let
  inherit (super) callPackage;
in rec
{
  ruby_ = self.ruby_2_6;

  bundler_ = callPackage ./bundler {
    ruby = ruby_;
  };

  bundix_ = self.bundix.override {
    bundler = bundler_;
  };
}
```

`bundler/default.nix` looks like this

```nix
{ buildRubyGem, ruby }:

buildRubyGem rec {
  inherit ruby;
  name = "${gemName}-${version}";
  gemName = "bundler";
  version = "2.0.1";
  source.sha256 = "1sjnfsyw80g56kj96gdfgxfb793h6d5fyyir4zf2x71wk4wq1qy7";
  dontPatchShebangs = true;

  postFixup = ''
    sed -i -e "s/activate_bin_path/bin_path/g" $out/bin/bundle
  '';
}
```

And I do have ruby 2.6, bundler 2.0.1 and bundix 2.4.1 on PATH correctly. Running `bundle` works as expected. However, running `bundix` afterwards does not:

```
λ ❯ bundix
Traceback (most recent call last):
        8: from /nix/store/i9ijrf8mf57b5rc8dggwn898z2476glb-bundix-2.4.1/bin/.bundix-wrapped:18:in `<main>'
        7: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
        6: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
        5: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
        4: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        3: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        2: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        1: from /nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.0.1) required by your /home/chris/dev/haven/nexus/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
Checked in 'GEM_PATH=/nix/store/65fs409354vgm39n9xvkv1jwrk2ypz8y-bundler-2.0.1/lib/ruby/gems/2.6.0:/nix/store/i9ijrf8mf57b5rc8dggwn898z2476glb-bundix-2.4.1/lib/ruby/gems/2.6.0:/nix/store/vvrsz1mmlnfa25hmp8qmxf89angcn46v-ruby-2.6.2/lib/ruby/gems/2.6.0', execute `gem env` for more information
```
It says it searches for Bundler in `/nix/store/65fs409354vgm39n9xvkv1jwrk2ypz8y-bundler-2.0.1/lib/ruby/gems/2.6.0`, which does indeed contain the Bundler 2.0.1 gem.

So, I'm not entirely sure what bundix (or rather rubygems) wants from me here. Any idea what is wrong?

**Comment by mkaito** [comment]
Apparently, a bug in RubyGems, fixed in RubyGems 3.0. I guess I'll wait until that lands in nixpkgs before I start using Bundler 2.0.

Sorry for the noise.
