### ISSUE TITLE
bundix -l fails when path has spaces

### ISSUE THREAD

**Issue by smithtim** [manveru/bundix#53]
`bundix -l` is trying to import `gemset.nix`, but failing because there are spaces in the path.

```
[nix-shell:~/main/Personal/Ruby Programs/youtube best]# bundix -l
$ nix-instantiate --eval -E builtins.toJSON(import /root/main/Personal/Ruby Programs/youtube best/gemset.nix)
error: getting status of '/root/main/Personal/Ruby': No such file or directory
Traceback (most recent call last):
	5: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/bin/.bundix-wrapped:18:in `<main>'
	4: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/bin/.bundix-wrapped:18:in `load'
	3: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/bin/bundix:112:in `<top (required)>'
	2: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:33:in `convert'
	1: from /nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:79:in `parse_gemset'
/nix/store/4rq534znwzp27a3y9c81agl30hab9cr6-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:122:in `sh': command execution failed: pid 4368 exit 1 (RuntimeError)
```

**Comment by alyssais** [comment]
@manveru can you remember your reasoning for 9399d6d36406a29201aa41ad5811e91932f6f621? Even if I fix the escaping here, Nix will still refuse to import an absolute path containing a space, but a relative path works fine.

**Comment by manveru** [comment]
@smithtim if you want, you can try out master, we can make a new release if it's working for you now.
