### ISSUE TITLE
gemset.nix missing source values

### ISSUE THREAD

**Issue by alexkehayias** [manveru/bundix#8]
Running the following commands inside a nix env that has `bundix` and `bundler` installed from nixpkgs results in a gemset.nix that is missing `source` values. 
### Command

```
bundler package
bundler lock
bundix -d
```
### Gemfile

```
source 'https://rubygems.org'
gem 'oauth2', '~> 1.0.0'
```
### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    jwt (1.5.4)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    rack (1.6.4)

PLATFORMS
  ruby

DEPENDENCIES
  oauth2 (~> 1.0.0)

BUNDLED WITH
   1.11.2
```
### gemset.nix

```
{
  faraday = {
    dependencies = ["multipart-post"];
  };
  jwt = {
  };
  multi_json = {
  };
  multi_xml = {
  };
  multipart-post = {
  };
  oauth2 = {
    dependencies = ["faraday" "jwt" "multi_json" "multi_xml" "rack"];
  };
  rack = {
  };
}
```

**Comment by alexkehayias** [comment]
Output from `bundix`

```
Skipping rack: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping oauth2: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping multipart-post: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping multi_xml: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping multi_json: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping jwt: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
Skipping faraday: invalid byte sequence in US-ASCII
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `[]'                                                 
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:37:in `block in fetch_local_hash'                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `each'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:34:in `fetch_local_hash'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:62:in `convert_rubygems'                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix/source.rb:6:in `convert'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:47:in `convert_spec'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:37:in `block in convert'                                          
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `reverse_each'                                              
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `with_object'                                               
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/lib/bundix.rb:36:in `convert'                                                   
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/lib/ruby/gems/2.3.1/gems/bundix
-2.0.8/bin/bundix:36:in `<top (required)>'                                             
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `load'
/nix/store/gz268gj4a8bkczf4k2akywbg4kr6cvvc-bundix-2.0.8/bin/bundix:13:in `<main>'
```

**Comment by alexkehayias** [comment]
This has to do with file encoding settings in the OS. See https://github.com/fastlane/fastlane/issues/227. 

Running `export LC_CTYPE=en_US.UTF-8 bundix -d` fixes the issue for me. Not sure how to make this a more permanent fix so closing this.
